[workspace]
resolver = "2"
members = [
    "gadget-core",
    "webb-gadget",
    "zk-gadget",
    "test-gadget",
    "playground",
    "protocols/mp-ecdsa"
]

[workspace.dependencies]
gadget-core = { path = "./gadget-core" }
webb-gadget = { path = "./webb-gadget" }
zk-gadget = { path = "./zk-gadget" }
zk-playground = { path = "./playground" }
mp-ecdsa-protocol = { path = "./protocols/mp-ecdsa" }

dkg-runtime-primitives = { git = "https://github.com/webb-tools/dkg-substrate" }
dkg-primitives = { git = "https://github.com/webb-tools/dkg-substrate" }

sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }
sc-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }
parity-scale-codec = "3.6.5"

mpc-net = { git = "https://github.com/webb-tools/zk-SaaS/" }
dist-primitives = { git = "https://github.com/webb-tools/zk-SaaS/" }
secret-sharing = { git = "https://github.com/webb-tools/zk-SaaS/" }
groth16 = { git = "https://github.com/webb-tools/zk-SaaS/" }

tokio-rustls = "0.24.1"
tokio = "1.32.0"
bincode2 = "2"
futures-util = "0.3.28"
serde = "1.0.188"
async-trait = "0.1.73"
log = "0.4.20"
parking_lot = "0.12.1"
futures = "0.3.28"
hex = "0.4.3"
uuid = "1.4.1"
bytes = "1.5.0"
serde_bytes = "0.11.12"
itertools = "0.12.0"
strum = "0.25.0"
