[workspace]
resolver = "2"
members = [
    "gadget-core",
    "webb-gadget",
    "zk-gadget",
    "test-gadget",
    "playground",
    "protocols/mp-ecdsa"
]

[workspace.dependencies]
gadget-core = { path = "./gadget-core" }
webb-gadget = { path = "./webb-gadget" }
zk-gadget = { path = "./zk-gadget" }
zk-playground = { path = "./playground" }
mp-ecdsa-protocol = { path = "./protocols/mp-ecdsa" }
pallet-jobs-rpc-runtime-api = { git = "https://github.com/webb-tools/tangle" }
tangle-primitives = { git = "https://github.com/webb-tools/tangle" }
tangle-testnet-runtime = { git = "https://github.com/webb-tools/tangle" }
tangle-mainnet-runtime = { git = "https://github.com/webb-tools/tangle" }

multi-party-ecdsa = { git = "https://github.com/webb-tools/cggmp-threshold-ecdsa/" }
round-based = { git = "https://github.com/webb-tools/round-based-protocol", features = [] }
curv = { package = "curv-kzen", version = "0.10.0" }

sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sc-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

sc-offchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sc-consensus-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sc-transaction-pool-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
parity-scale-codec = "3.6.5"

pallet-im-online = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"  }

mpc-net = { git = "https://github.com/webb-tools/zk-SaaS/" }
dist-primitives = { git = "https://github.com/webb-tools/zk-SaaS/" }
secret-sharing = { git = "https://github.com/webb-tools/zk-SaaS/" }
groth16 = { git = "https://github.com/webb-tools/zk-SaaS/" }

tokio-rustls = "0.24.1"
tokio = "1.32.0"
bincode2 = "2"
futures-util = "0.3.28"
serde = "1.0.188"
async-trait = "0.1.73"
log = "0.4.20"
parking_lot = "0.12.1"
futures = "0.3.28"
hex = "0.4.3"
uuid = "1.4.1"
bytes = "1.5.0"
serde_bytes = "0.11.12"
itertools = "0.12.0"
strum = "0.25.0"
clap = "4.0.32"
hex-literal = "0.4.1"
rand = "0.8.5"
jsonrpsee = "0.16.2"
libp2p = "0.53.1"