[package]
name = "mp-ecdsa-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
application = []

[dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
webb-gadget = { workspace = true }
gadget-core = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
multi-party-ecdsa = { workspace = true }
round-based = { workspace = true }
curv = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
strum = { workspace = true }
bincode2 = { workspace = true }
clap = { workspace = true }
hex-literal = { workspace = true }
rand = { workspace = true }
jsonrpsee = { workspace = true, features = ["server"] }
linked-hash-map = { workspace = true }

pallet-jobs-rpc-runtime-api = { workspace = true }
tangle-primitives = { workspace = true }
tangle-testnet-runtime = { workspace = true }
tangle-mainnet-runtime = { workspace = true }

sp-core = { workspace = true }
sp-api = { workspace = true }
sp-runtime = { workspace = true }
sp-application-crypto = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-keyring = { workspace = true }
sp-timestamp = { workspace = true }
sp-blockchain = { workspace = true }
sp-block-builder = { workspace = true }

sc-client-api = { workspace = true }
sc-consensus-aura = { workspace = true }
sc-consensus-grandpa = { workspace = true }
sc-executor = { workspace = true }
sc-network = { workspace = true }
sc-network-common = { workspace = true }
sc-network-sync = { workspace = true }
sc-service = { workspace = true }
sc-telemetry = { workspace = true }
sc-transaction-pool-api = { workspace = true }
sc-cli = { workspace = true }
sc-consensus = { workspace = true }
sc-transaction-pool = { workspace = true }
sc-basic-authorship = { workspace = true }
sc-offchain = { workspace = true }
sc-rpc-api = { workspace = true }


parity-scale-codec = { workspace = true }
substrate-frame-rpc-system = { workspace = true }
pallet-transaction-payment-rpc = { workspace = true }
pallet-im-online = { workspace = true }
serde = { version = "1.0.193", features = ["derive"] }

[build-dependencies]
substrate-build-script-utils = { workspace = true }