[package]
name = "mp-ecdsa-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
application = []

[dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
webb-gadget = { workspace = true }
gadget-core = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
multi-party-ecdsa = { workspace = true }
round-based = { workspace = true }
curv = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
bincode2 = { workspace = true }
linked-hash-map = { workspace = true }

pallet-jobs-rpc-runtime-api = { workspace = true, default-features = false }
tangle-primitives = { workspace = true, default-features = false }

sp-core = { workspace = true, default-features = false }
sp-api = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-application-crypto = { workspace = true, default-features = false }
sp-consensus-aura = { workspace = true, default-features = false }

sc-client-api = { workspace = true, default-features = false }
sc-network = { workspace = true, default-features = false }
sc-network-common = { workspace = true, default-features = false }
sc-network-sync = { workspace = true, default-features = false }


parity-scale-codec = { workspace = true, default-features = false }
serde = { version = "1.0.193", features = ["derive"] }

[build-dependencies]
substrate-build-script-utils = { workspace = true }